[package]
name = "rust_code"
version = "0.1.0"
edition = "2021"


[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
maturin = "0.14"
colored = { version = "2.2.0"}
rpassword = "7.3.1"
